### ISSUE TITLE
android4.4(api19)无法安装，也无法真机、模拟机调试

### ISSUE THREAD

**Issue by WildChen** [zhangliangming/HappyPlayer5#18]
调试出错信息：
05-01 10:29:26.500 8130-8130/com.zlm.hp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zlm.hp, PID: 8130
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.zlm.hp/com.zlm.hp.ui.SplashActivity}: java.lang.ClassNotFoundException: Didn't find class "com.zlm.hp.ui.SplashActivity" on path: DexPathList[[zip file "/data/app/com.zlm.hp-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.zlm.hp-2, /vendor/lib, /data/cust/lib, /system/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2196)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2319)
        at android.app.ActivityThread.access$1100(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5342)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zlm.hp.ui.SplashActivity" on path: DexPathList[[zip file "/data/app/com.zlm.hp-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.zlm.hp-2, /vendor/lib, /data/cust/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1064)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2319) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5342) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
        at dalvik.system.NativeStart.main(Native Method) 
安装出错信息：
![_20180501104743](https://user-images.githubusercontent.com/28303119/39459301-1d81444a-4d2d-11e8-9888-62abcf9878d0.png)
但是在台电平板android5.0(API21)和小米5s plus android7.0(API24)能安装运行，也能调试。
求解？？？

**Comment by zhangliangming** [comment]
https://www.jianshu.com/p/cddfc89ce947

**Comment by zhangliangming** [comment]
@WildChen 你看看这个帖子，能不能解决你的问题。

**Comment by WildChen** [comment]
@zhangliangming 已解决，谢谢老哥！

**Comment by zhangliangming** [comment]
@WildChen 不用客气
